#!/usr/bin/env python3
import sys
from pathlib import Path


def add(dmodulefile, filename):
    filepath = Path(filename)
    if not filepath.exists():
        filepath.touch()
    lines = filepath.read_text().split('\n')
    loaded = False
    for line in lines:
        if line == f'source_env {dmodulefile}':
            # already loaded, do nothing
            loaded = True
    if not loaded:
        lines.append(f'source_env {dmodulefile}')
    filepath.write_text('\n'.join(lines) + '\n')


def remove(dmodulefile, filename):
    filepath = Path(filename)
    if not filepath.exists():
        # no .envrc, so nothing to unload
        return
    lines = filepath.read_text().split('\n')
    lines_to_write = []
    for line in lines:
        if dmodulefile not in line:
            lines_to_write.append(line)
    filepath.write_text('\n'.join(lines_to_write))


commands = {'add': add,
            'remove': remove}


def main(args):
    command = args[0]
    dmodulefile = args[1]
    filename = args[2]
    return commands[command](dmodulefile, filename)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
