* direnv Modules

"[[https://direnv.net/][direnv]] is an extension for your shell. It augments existing shells with a new feature that can load and unload environment variables depending on the current directory."

"The [[http://modules.sourceforge.net/][Environment Modules]] package is a tool that simplify shell initialization and lets users easily modify their environment during the session with modulefiles.  Modules can be loaded and unloaded dynamically and atomically, in an clean fashion."

This is an Environment Modules-like interface built on top of direnv, for those who want the best of both worlds.

Here's a quick demo

#+begin_export html
<a href="https://asciinema.org/a/405131" target="_blank"><img src="https://asciinema.org/a/405131.svg" /></a>
#+end_export

** Setup

Create dmodulefiles in a directory structure like this:

#+begin_src sh
  mkdir /opt/dmodulefiles
  mkdir /opt/dmodulefiles/tool_a
  mkdir /opt/dmodulefiles/tool_b
#+end_src

Inside the tool_a and tool_b directories, create text files named for the version of the tool the dmodulefile is for.  In that text file write shell syntax code to set environment variable that are needed by the tool.  For example, in =/opt/dmodulefiles/tools_a/1.3= you might have:

#+begin_src sh
  export PATH=/path/to/tool_a/bin:$PATH
  export LM_LICENSE_FILE=4567@license_server
#+end_src

Then, in your =~/.profile= add this line:

#+begin_src sh
  export DMODULEPATH=/top/dmodulefiles
#+end_src

** Usage

Everything is handled by the =dm= (for direnv module) command.  These are its sub commands:

*** avail

List all available modulefiles in the current DMODULEPATH

*** help

Print the usage of each sub-command. If an argument is given, print the Module-specific help information for the dmodulefile.

*** list

List loaded modules.

*** load modulefile...

Load modulefile into the shell environment.

*** purge

Unload all loaded modulefiles.

*** reload

Unload then load all loaded modulefiles.

*** unload modulefile...

Remove modulefile from the shell environment.
