#!/bin/sh
######################################################################
# load two dmodules, unload one
######################################################################
set -e
. ./test-funcs
# start clean
rm -f .envrc
PATH=../:$PATH DMODULEPATH=./dmodulefiles/ ../dm load bar/1.0
PATH=../:$PATH DMODULEPATH=./dmodulefiles/ ../dm load foo/2.3
EXPECTED_TEXT_1="source_env dmodulefiles/bar/1.0"
EXPECTED_TEXT_2="source_env dmodulefiles/foo/2.3"
if ! grep -qs "$EXPECTED_TEXT_1" .envrc; then
    end_test "$0" fail
fi
if ! grep -qs "$EXPECTED_TEXT_2" .envrc; then
    end_test "$0" fail
fi
BAR=$(direnv exec . sh -c 'echo $BAR')
if [ ! "$BAR" = "bar 1.0 loaded" ]; then
    end_test "$0" fail
fi
FOO=$(direnv exec . sh -c 'echo $FOO')
if [ ! "$BAR" = "foo 2.3 loaded" ]; then
    end_test "$0" fail
fi
