#!/bin/sh
set -e

# get functions common to all tests
. ./test-funcs

# start clean
rm -f .envrc

PATH=../:$PATH DMODULEPATH=./dmodulefiles/ ../dm load bar/1.1
EXPECTED_TEXT="source_env dmodulefiles/bar/1.1"
if ! grep -qs "$EXPECTED_TEXT" .envrc; then
    end_test "$0" fail
fi
# can't quite figure out why sometimes I need this in order to clean
# up, and sometimes I don't ¯\_(ツ)_/¯
direnv deny .

PATH=../:$PATH DMODULEPATH=./dmodulefiles/ ../dm unload bar/1.1
if grep -qs "$EXPECTED_TEXT" .envrc; then
    end_test "$0" fail
fi
end_test "$0" pass
